version: '3.9'

services:
  postgres:
    image: postgres:alpine3.17
    container_name: articles_postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  app:
    build: .
    container_name: articles_app
    restart: always
    depends_on:
      - postgres
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - articles-proxy

  nginx:
    container_name: artucles_nginx
    image: nginx:alpine
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - articles-proxy
    ports:
      - 8888:8888

volumes:
  postgres:
    driver: local

networks:
  articles-proxy:
    driver: bridge
